name: Documentation build

on:
    push:
        branches: [main]
        paths:
            - ".github/**"
            - "website/**"
    pull_request:
        branches: [main]
        paths:
            - ".github/**"
            - "website/**"

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            EM_VERSION: 3.1.7
            EM_CACHE_FOLDER: "emsdk-cache"
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "recursive"
                  fetch-depth: 0
            - name: Setup cache
              id: cache-system-libraries
              uses: actions/cache@v3
              with:
                  path: ${{env.EM_CACHE_FOLDER}}
                  key: ${{env.EM_VERSION}}-${{ runner.os }}
            - uses: mymindstorm/setup-emsdk@v11
              with:
                  version: ${{env.EM_VERSION}}
                  actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
            - run: make
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: yarn
                  cache-dependency-path: website/yarn.lock
            - name: Install dependencies
              working-directory: website
              run: yarn install --frozen-lockfile
            - name: Build website
              working-directory: website
              run: yarn build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: website/build
                  force_orphan: true
